server:
  port: 8086

spring:
  datasource:
    url: jdbc:postgresql://localhost:5446/books_manager_settings_db
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: update

springdoc:
  enableNativeSupport: true
  swagger-ui:
    path: /swagger-ui